[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bci-desktop-pet"
dynamic = ["version"]

requires-python = ">= 3.8"
dependencies = [
    pillow>=10.2.0,
    setproctitle>=1.3.3
]

[project.scripts]
bci-pet = "pet"
